server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    enabled: false # with kubernetes, we don't need eureka server discovery.

spring:
  application:
    name: notification-service
  config:
    import: "classpath:rabbitmq-config.yml"

  main:
    banner-mode: off
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5432/notificationdb}
    username: ${NOTIFICATION_DB_USERNAME:msstrainz}
    password: ${NOTIFICATION_DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: false
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      transaction-isolation: TRANSACTION_READ_COMMITTED

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[%X{ traceId:-},%X{ spanId:-}]"