server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: api-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: "[%X{ traceId:-},%X{ spanId:-}]"