apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      restartPolicy: Always
      containers:
        - name: customer-service
          image: wanemar/customer:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CUSTOMER_DB_URL
              value: jdbc:postgresql://postgres-service:5432/customerdb
            - name: CUSTOMER_DB_USERNAME
              value: msstrainz
            - name: CUSTOMER_DB_PASSWORD
              value: password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"