apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      restartPolicy: Always
      containers:
        - name: customer-service
          image: wanemar/customer:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: common-env-config
                optional: false
          env:
            - name: CUSTOMER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: cdb-url
            - name: CUSTOMER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: cdb-username
            - name: CUSTOMER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: cdb-password
