apiVersion: apps/v1
kind: Deployment

metadata:
  name: fraud-service
  labels:
    app: fraud-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      restartPolicy: Always
      containers:
        - name: fraud-service
          image: wanemar/fraud:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          envFrom:
            - configMapRef:
                name: common-env-config
                optional: false
          env:
            - name: FRAUD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: fraud-secrets
                  key: fdb-url
            - name: FRAUD_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fraud-secrets
                  key: fdb-username
            - name: FRAUD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fraud-secrets
                  key: fdb-password