apiVersion: v1
kind: Service

metadata:
  name: fraud-service
  labels:
    app: fraud-service

spec:
  type: NodePort
  selector:
    app: fraud-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001